### ISSUE TITLE
Style of header title not good

### ISSUE THREAD

**Issue by pedzed** [CreativeDream/jquery.modal#4]
I am using Foundation and it uses a black color for headers. The problem is that _jquery.modal_ doesn't specify a white color.

![black header jquery.modal](https://i.imgur.com/wSJf028.png)

This problem can be easily fixed by adding `color: #fff` or something similar to the h3.

``` css
#modal-window .modal-box .modal-title h3 {
    color: #fff;
}
```
